feature: add kalao adapters
dappradar/nft-sales-adapters pull request #66
Opened 2022-07-02 17:08 UTC by kashyapjii

Add Kalao Adapter

2022-07-02 17:13 UTC, kashyapjii commented
Add RadioCaca Market

2022-07-13 08:05 UTC, liutaurasjanuskas commented on adapters/kalao-avalanche/index.js
> +        const pubrchaseLog = transaction.logs.find(
Mistype

2022-07-20 10:36 UTC, Mintiss requested changes

2022-07-20 10:36 UTC, Mintiss commented on adapters/kalao-avalanche/index.js
> +            price_usd: priceUsd,
`token_symbol` is undefined
`price` and `price_usd` are null
Make sure to pass the tests before requesting a review

2023-02-27 08:09 UTC, closed without merging